# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

Target.create("os"=> "Windows 2003", "browser"=> "chrome", "browser_version"=> "2.0.")
Target.create("os"=> "Windows 2003", "browser"=> "firefox", "browser_version"=> "2.0.")
Target.create("os"=> "Windows 2003", "browser"=> "chrome", "browser_version"=> "3.0.")
Target.create("os"=> "Windows 2003", "browser"=> "firefox", "browser_version"=> "3.0.")
Target.create("os"=> "Windows 2003", "browser"=> "chrome", "browser_version"=> "3.5.")
Target.create("os"=> "Windows 2003", "browser"=> "firefox", "browser_version"=> "3.5.")
Target.create("os"=> "Windows 2003", "browser"=> "chrome", "browser_version"=> "3.6.")
Target.create("os"=> "Windows 2003", "browser"=> "firefox", "browser_version"=> "3.6.")
Target.create("os"=> "Windows 2003", "browser"=> "firefoxproxy", "browser_version"=> "2.0.")
Target.create("os"=> "Windows 2003", "browser"=> "firefoxproxy", "browser_version"=> "3.0.")
Target.create("os"=> "Windows 2003", "browser"=> "firefoxproxy", "browser_version"=> "3.5.")
Target.create("os"=> "Windows 2003", "browser"=> "firefoxproxy", "browser_version"=> "3.6.")
Target.create("os"=> "Windows 2003", "browser"=> "googlechrome", "browser_version"=> "")
Target.create("os"=> "Windows 2003", "browser"=> "iehta", "browser_version"=> "6.")
Target.create("os"=> "Windows 2003", "browser"=> "iexplore", "browser_version"=> "6.")
Target.create("os"=> "Windows 2003", "browser"=> "iehta", "browser_version"=> "7.")
Target.create("os"=> "Windows 2003", "browser"=> "iexplore", "browser_version"=> "7.")
Target.create("os"=> "Windows 2003", "browser"=> "iehta", "browser_version"=> "8.")
Target.create("os"=> "Windows 2003", "browser"=> "iexplore", "browser_version"=> "8.")
Target.create("os"=> "Windows 2003", "browser"=> "iexploreproxy", "browser_version"=> "6.")
Target.create("os"=> "Windows 2003", "browser"=> "iexploreproxy", "browser_version"=> "7.")
Target.create("os"=> "Windows 2003", "browser"=> "iexploreproxy", "browser_version"=> "8.")
Target.create("os"=> "Windows 2003", "browser"=> "opera", "browser_version"=> "10.")
Target.create("os"=> "Windows 2003", "browser"=> "opera", "browser_version"=> "9.")
Target.create("os"=> "Windows 2003", "browser"=> "safari", "browser_version"=> "3.")
Target.create("os"=> "Windows 2003", "browser"=> "safari", "browser_version"=> "4.")
Target.create("os"=> "Windows 2003", "browser"=> "safariproxy", "browser_version"=> "3.")
Target.create("os"=> "Windows 2003", "browser"=> "safariproxy", "browser_version"=> "4.")
Target.create("os"=> "Windows 2003", "browser"=> "safariproxy", "browser_version"=> "5.")
Target.create("os"=> "Linux", "browser"=> "chrome", "browser_version"=> "3.0.")
Target.create("os"=> "Linux", "browser"=> "firefox", "browser_version"=> "3.0.")
Target.create("os"=> "Linux", "browser"=> "firefoxproxy", "browser_version"=> "3.0.")
